version: '2.0'
services:
  chatgpt-on-wechat:
    build:
      context: ./
      dockerfile: Dockerfile.alpine
    image: zhayujie/chatgpt-on-wechat-voice-reply
    container_name: chatgpt-on-wechat-voice-reply
    environment:
      OPEN_AI_API_KEY: 'YOUR API KEY'
      OPEN_AI_PROXY: ''
      SINGLE_CHAT_PREFIX: '[""]'
      SINGLE_CHAT_REPLY_PREFIX: '"[圆圆AI] "'
      GROUP_CHAT_PREFIX: '[""]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: "False"
      CHARACTER_DESC: '你是圆圆AI，集成ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      VOICE_REPLY_VOICE: 'true'
      BAIDU_APP_ID: 'YOUR BAIDU APP ID'
      BAIDU_API_KEY: 'YOUR BAIDU API KEY'
      BAIDU_SECRET_KEY: 'YOUR BAIDU SERVICE KEY'